services:
    mongo:
        image: mongo:6.0
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    product-service:
        build: ./opencart-product-service
        container_name: product-service
        restart: on-failure
        ports:
            - "3000:3000"
        environment:
            - DB_STRING=mongodb://mongo:27017/opencart
        depends_on:
            - mongo

    order-service:
        build: ./opencart-order-service
        container_name: order-service
        restart: on-failure
        ports:
            - "3001:3001"
        environment:
            - MONGODB_URI=mongodb://mongo:27017/opencart
        depends_on:
            - mongo

    payment-service:
        build: ./opencart-payment-service
        container_name: payment-service
        restart: on-failure
        ports:
            - "3002:3002"
        environment:
            - DB_STRING=mongodb://mongo:27017/opencart
        depends_on:
            - mongo

    frontend:
        build: ./frontend
        container_name: frontend
        restart: on-failure
        ports:
            - "5173:5173"
        depends_on:
            - product-service
            - order-service
            - payment-service

volumes:
  mongo-data:
